name: ai_ml_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Jupyter
  - jupyterlab
  - notebook
  - jupyter
  - ipykernel
  - ipywidgets

  # Core Data Science
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - statsmodels

  # NLP
  - nltk

  # Web Scraping
  - beautifulsoup4
  - lxml
  - html5lib

  # Excel/File Handling
  - openpyxl

  # Web/App Frameworks
  - flask
  - streamlit

  # Visualization
  - plotly
  - dash

  # Misc
  - nbformat>=4.2.0
  - pip

  - pip:
      - kaggle
      - python-dotenv